services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - ./database/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: ristoeasy
    ports:
      - 5432:5432
    networks:
      - app
  ristoeasy:
    build: .
    depends_on:
      - postgres
    ports:
      - 5000:3000
    networks:
      - app
    environment:
      env: production


networks:
  app:

volumes:
  data:
