services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - ./database/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: ristoeasy
    ports:
      - 5432:5432
    networks:
      - app
  ristoeasy:
    build: .
    ports:
      - 8080:3000
    networks:
      - app
    environment:
      DBHOST: postgres
      DBUSER: postgres
      DBPASSWORD: postgres
      DBNAMe: ristoeasy

networks:
  app:

volumes:
  data:
